version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1000:3000"
    tty: true
    volumes:
      - ./vanilla:/vanilla
    command: bash -c "npm install && npm run start"